import { afterEach, describe, expect, it, vi } from 'vitest';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';

const { requestMock } = vi.hoisted(() => ({ requestMock: vi.fn() }));
vi.mock('node:https', () => ({ request: requestMock }));

import { CANVAS_USER_AGENT, canvasHttpsTransport, requestCanvasApi, type CanvasHttpReply } from './canvasProxy';

const base = 'https://q.utoronto.ca';
const address = { address: '93.184.216.34', family: 4 };
const resolve = async () => [address];
const upstream = (status: number, contentType: string, body: string): CanvasHttpReply => ({
  status, headers: { 'content-type': contentType }, body: Buffer.from(body),
});
afterEach(() => vi.clearAllMocks());

describe('Quercus transport compatibility', () => {
  it('sends an honest stable User-Agent through the default HTTPS transport while retaining DNS pinning', async () => {
    requestMock.mockImplementation((_url, _options, onResponse) => {
      const request = Object.assign(new EventEmitter(), {
        end: () => {
          const response = Object.assign(new PassThrough(), { statusCode: 200, headers: { 'content-type': 'application/json' } });
          onResponse(response);
          response.end('{"id":1}');
        },
        destroy: vi.fn(),
      });
      return request;
    });
    const target = new URL('/api/v1/users/self/profile', base);
    const result = await canvasHttpsTransport(target, {
      headers: { Authorization: 'Bearer test-only-token', Accept: 'application/json' },
      address, signal: new AbortController().signal, maxBytes: 1000,
    });
    expect(result.status).toBe(200);
    const [url, options] = requestMock.mock.calls[0];
    expect(url.href).toBe(`${base}/api/v1/users/self/profile`);
    expect(options.method).toBe('GET');
    expect(options.headers).toMatchObject({
      Authorization: 'Bearer test-only-token', Accept: 'application/json', 'User-Agent': CANVAS_USER_AGENT,
    });
    expect(CANVAS_USER_AGENT).toMatch(/^ClassSkip\//);
    expect(CANVAS_USER_AGENT).not.toMatch(/Mozilla|Chrome|Safari/i);
    const callback = vi.fn();
    options.lookup('q.utoronto.ca', { all: true }, callback);
    expect(callback).toHaveBeenCalledWith(null, [address]);
  });

  it('does not tell the user their token is wrong when CloudFront rejects a missing User-Agent', async () => {
    const body = '<html><title>403 ERROR</title><body>Request blocked. You have not provided a valid user agent. Generated by cloudfront. Private diagnostics must not be displayed.</body></html>';
    const transport = vi.fn(async () => upstream(403, 'text/html', body));
    const error = await requestCanvasApi(base, '/api/v1/users/self/profile', 'test-only-token', { resolve, transport }).catch(error => error) as Error & { code: string; status: number };
    expect(error).toMatchObject({ code: 'request_rejected', status: 502 });
    expect(error.message).not.toMatch(/test-only-token|Private diagnostics|<html>|检查令牌/);
    expect(transport).toHaveBeenCalledTimes(1);
  });

  it('distinguishes other HTML gateway refusals from Canvas permission responses', async () => {
    const transport = vi.fn(async () => upstream(403, 'text/html; charset=utf-8', '<html>Access denied by the edge. Private diagnostics.</html>'));
    const error = await requestCanvasApi(base, '/api/v1/courses', 'test-only-token', { resolve, transport }).catch(error => error) as Error & { code: string; status: number };
    expect(error).toMatchObject({ code: 'connection_rejected', status: 502 });
    expect(error.message).not.toMatch(/Private diagnostics|<html>|检查令牌/);
  });

  it('keeps Canvas JSON invalid-token responses classified as unauthorized', async () => {
    const transport = vi.fn(async () => upstream(401, 'application/json; charset=utf-8', '{"errors":[{"message":"Invalid access token."}]}'));
    await expect(requestCanvasApi(base, '/api/v1/users/self/profile', 'test-only-token', { resolve, transport })).rejects.toMatchObject({ code: 'unauthorized', status: 401 });
  });

  it('keeps Canvas JSON permission responses distinct from invalid-token responses', async () => {
    const transport = vi.fn(async () => upstream(403, 'application/json', '{"errors":[{"message":"user not authorized to perform that action"}]}'));
    await expect(requestCanvasApi(base, '/api/v1/courses', 'test-only-token', { resolve, transport })).rejects.toMatchObject({ code: 'forbidden', status: 403 });
  });
});
